name: mobProtect
version: 2.2
description: allows you to protect mobs in worldguard regions!
author: xize
authors: [] 
website:

main: tv.mineinthebox.mobProtect.mobProtect
database: false
depend: []
softdepend: [WorldGuard]

commands:
  mobprotect:
    description: global commands for mobProtect
    aliases: [mp]
    permission:
    permission-message:

permissions: